### ISSUE TITLE
No data for the guide notebook

### ISSUE THREAD

**Issue by auranic** [Qotov/scEvoNet#1]
I can not find the data for two datasets used in the notebook:
gastrulation_df = pd.read_pickle('test_data_12.pkl')
neurulation_df = pd.read_pickle('test_data_20.pkl')
Can you please provide them somewhere?

**Comment by Qotov** [comment]
I put it here https://www.dropbox.com/sh/tt1cgrxp2qu9r0f/AADJhRbiWTwebLhD8dPfAJLCa?dl=0
